volumes:
  log_volume:
  grafana_data:

networks:
  monitoring:
  backend:

services:
  fx:
    build: ./fx
    volumes:
      - log_volume:/var/log
    networks:
      - monitoring
      - backend

  web:
    depends_on:
      - fx
    build: ./gateway
    volumes:
      - log_volume:/var/log
    ports:
      - "8080:8080"
    networks:
      - monitoring
      - backend
    environment:
      - "GIN_MODE=release"
    command: [ "/bin/sh", "-c", "/app/run_web_server -host fx:50051 > /var/log/gateway.log" ]

  # logging and monitoring services
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - log_volume:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  grafana:
    depends_on:
      - monitoring
      - prometheus
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring