// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: fx.proto

package rpc_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FxServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCurrencyCode string `protobuf:"bytes,1,opt,name=SourceCurrencyCode,proto3" json:"SourceCurrencyCode,omitempty"`
	TargetCurrencyCode string `protobuf:"bytes,2,opt,name=TargetCurrencyCode,proto3" json:"TargetCurrencyCode,omitempty"`
}

func (x *FxServiceRequest) Reset() {
	*x = FxServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FxServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FxServiceRequest) ProtoMessage() {}

func (x *FxServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FxServiceRequest.ProtoReflect.Descriptor instead.
func (*FxServiceRequest) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{0}
}

func (x *FxServiceRequest) GetSourceCurrencyCode() string {
	if x != nil {
		return x.SourceCurrencyCode
	}
	return ""
}

func (x *FxServiceRequest) GetTargetCurrencyCode() string {
	if x != nil {
		return x.TargetCurrencyCode
	}
	return ""
}

type FxServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCurrencyCode string  `protobuf:"bytes,1,opt,name=SourceCurrencyCode,proto3" json:"SourceCurrencyCode,omitempty"`
	TargetCurrencyCode string  `protobuf:"bytes,2,opt,name=TargetCurrencyCode,proto3" json:"TargetCurrencyCode,omitempty"`
	Rate               float64 `protobuf:"fixed64,3,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *FxServiceResponse) Reset() {
	*x = FxServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FxServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FxServiceResponse) ProtoMessage() {}

func (x *FxServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FxServiceResponse.ProtoReflect.Descriptor instead.
func (*FxServiceResponse) Descriptor() ([]byte, []int) {
	return file_fx_proto_rawDescGZIP(), []int{1}
}

func (x *FxServiceResponse) GetSourceCurrencyCode() string {
	if x != nil {
		return x.SourceCurrencyCode
	}
	return ""
}

func (x *FxServiceResponse) GetTargetCurrencyCode() string {
	if x != nil {
		return x.TargetCurrencyCode
	}
	return ""
}

func (x *FxServiceResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_fx_proto protoreflect.FileDescriptor

var file_fx_proto_rawDesc = []byte{
	0x0a, 0x08, 0x66, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x10, 0x46, 0x78,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2e,
	0x0a, 0x12, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x87,
	0x01, 0x0a, 0x11, 0x46, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x52, 0x61, 0x74, 0x65, 0x32, 0x41, 0x0a, 0x09, 0x46, 0x78, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x46, 0x78, 0x52, 0x61,
	0x74, 0x65, 0x12, 0x11, 0x2e, 0x46, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x46, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fx_proto_rawDescOnce sync.Once
	file_fx_proto_rawDescData = file_fx_proto_rawDesc
)

func file_fx_proto_rawDescGZIP() []byte {
	file_fx_proto_rawDescOnce.Do(func() {
		file_fx_proto_rawDescData = protoimpl.X.CompressGZIP(file_fx_proto_rawDescData)
	})
	return file_fx_proto_rawDescData
}

var file_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fx_proto_goTypes = []interface{}{
	(*FxServiceRequest)(nil),  // 0: FxServiceRequest
	(*FxServiceResponse)(nil), // 1: FxServiceResponse
}
var file_fx_proto_depIdxs = []int32{
	0, // 0: FxService.GetFxRate:input_type -> FxServiceRequest
	1, // 1: FxService.GetFxRate:output_type -> FxServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fx_proto_init() }
func file_fx_proto_init() {
	if File_fx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FxServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FxServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_proto_goTypes,
		DependencyIndexes: file_fx_proto_depIdxs,
		MessageInfos:      file_fx_proto_msgTypes,
	}.Build()
	File_fx_proto = out.File
	file_fx_proto_rawDesc = nil
	file_fx_proto_goTypes = nil
	file_fx_proto_depIdxs = nil
}
