### Send POST request with json body
POST http://localhost:8080/api/v1/fx
Content-Type: application/json

{
  "SourceCurrency": "CHF",
  "TargetCurrency": "USD",
  "SourceAmount": 100.09
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

